---
version: '3.7'
services:
  duckdnsdo:
    image: mavnt/duckdnsdo:latest

    # echo url="https://www.duckdns.org/update?domains=$domains&token=$token&ip=" | curl -k -o /workdir/duck.log -K -
    # sleep $seconds
    environment:
      - domains=...
      - token=...
      - seconds=300
